import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import 'aos/dist/aos.css';
import SmoothScrollWrapper from './SmoothScrollWrapper';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScrollWrapper>
          <Header />
          {children}
          <Footer />
        </SmoothScrollWrapper>
      </body>
    </html>
  );
}
